name: 'Gradle App Versioning Action'
author: 'FallenVEye'
description: 'A GitHub action for versioning gradle based application by gradle.properties file'
inputs:
  snapshot:
    description: 'Should the new version be a snapshot'
    required: false
    default: false
  version_type:
    description: 'New version type. One of: major, minor, patch'
    required: true
  unique_snapshot:
    description: |
      Add commit hash to version. Useful when publishing to maven or similar repo
      Options:
        - commit    | unique by commit hash 
        - date-time | unique by date-time of action run
    required: false
  save_version_to_gh_output:
    description: 'Shoud action save calculated version to $GITHUB_OUTPUT file? If so, version can be accessed by steps.id.outputs.version'
    required: false
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.snapshot }}
    - ${{ inputs.version-type}}