

name: 'Publish workflow'

on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Publish
        id: publish
        uses: actions/publish-immutable-action@0.0.3